# Generated by Django 5.1.7 on 2025-04-25 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=100)),
                ('grade_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('teaching_load', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=9)),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.timeslot')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('advisory_id', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.teacher')),
            ],
        ),
    ]
