# Generated by Django 5.1.7 on 2025-04-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_section_subject_teacher_schedule_advisory'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisory',
            name='school_year',
            field=models.CharField(default='2023-2024', max_length=9),
            preserve_default=False,
        ),
    ]
